name: 'dbt_adventure_works'
version: '1.0.0'
config-version: 2

profile: 'dbt_bigquery'

# Directories for dbt to look for files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory to store compiled SQL files
target-path: "target"

# Directories to clean with `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models by directory
models:
  dbt_adventure_works:
    # Configuration for staging models
    staging:
      +schema: dev_adventure_works
      +materialized: view
      person:
        materialized: view
        convert_spatial_location:
          materialized: table
          path: models/staging/person/convert_spatial_location.py

    # Configuration for intermediate models
    intermediate:
      +schema: dev_adventure_works
      +materialized: view

    # Configuration for final (marts) models
    marts:
      +schema: dev_adventure_works
      +materialized: table

# Configuring seed files
seeds:
  dbt_adventure_works:
    sap_adventure_works:
      +schema: stg_adventure_works
