dbt_bigquery:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: robotic-parsec-433018-g3
      dataset: dev_adventure_works
      threads: 64
      keyfile: keys/dbt-service-account.json
      location: US

    prod:
      type: bigquery
      method: service-account
      project: robotic-parsec-433018-g3
      dataset: prod_adventure_works
      threads: 64
      keyfile: keys/dbt-service-account.json
      location: US

    stg:
      type: bigquery
      method: service-account
      project: robotic-parsec-433018-g3
      dataset: stg_adventure_works
      threads: 64
      keyfile: keys/dbt-service-account.json
      location: US

  target: dev
