version: 2

models:
  - name: dim_sales_territory
    description: "This table contains detailed information about sales territories, including associated regions and financial performance metrics."
    columns:
      - name: sales_territory_id
        description: "Unique identifier for the sales territory."
        tests:
          - unique
          - not_null

      - name: sales_territory_name
        description: "The name of the sales territory."
        tests:
          - not_null

      - name: sales_territory_group
        description: "The group to which the sales territory belongs."
        tests:
          - not_null

      - name: country_region_id
        description: "Identifier for the country or region associated with the sales territory."
        tests:
          - not_null

      - name: country_region_name
        description: "Name of the country or region associated with the sales territory."
        tests:
          - not_null

      - name: sales_ytd
        description: "Year-to-date sales for the sales territory."
        tests:
          - not_null

      - name: sales_last_year
        description: "Sales for the last year in the sales territory."
        tests:
          - not_null

      - name: cost_ytd
        description: "Year-to-date costs for the sales territory."
        tests:
          - not_null

      - name: cost_last_year
        description: "Costs for the last year in the sales territory."
        tests:
          - not_null
