version: 2

models:
  - name: int_customer_info
    description: "Intermediate view in the dev_adventure_works schema containing detailed customer information."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for the customer."
        tests:
          - not_null
          - unique
      - name: person_id
        description: "Foreign key to person entity. Can be null."
        tests:
          - relationships:
              to: ref('stg_person')
              field: business_entity_id
      - name: store_id
        description: "Foreign key to store entity. Can be null."
        tests:
          - relationships:
              to: ref('stg_store')
              field: business_entity_id
      - name: sales_territory_id
        description: "Foreign key to sales territory entity. Can be null."
        tests:
          - relationships:
              to: ref('stg_sales_territory')
              field: sales_territory_id
      - name: first_name
        description: "First name of the customer."
      - name: middle_name
        description: "Middle name of the customer."
      - name: last_name
        description: "Last name of the customer."
      - name: name_title
        description: "Title of the customer."
      - name: name_style
        description: "Style of the customer's name."
      - name: person_type
        description: "Type of person (individual or organization)."
      - name: name_suffix
        description: "Suffix of the customer's name."
      - name: email_promotion
        description: "Indicates whether the customer is open to email promotions."
      - name: additional_contact_info
        description: "Additional contact information of the customer."
      - name: demographics
        description: "Demographic information of the customer."
      - name: country_region_id
        description: "Identifier for the country or region associated with the sales territory."
      - name: country_region_name
        description: "Name of the country or region associated with the sales territory."
