version: 2

models:
  - name: agg_sales_by_sales_person
    description: "aggregated sales data by sales person, including sales details by week, region, and total sales value."
    columns:
      - name: sales_person_id
        description: "unique identifier for the sales person."
        tests:
          - not_null

      - name: first_name
        description: "first name of the sales person."
        tests:
          - not_null

      - name: last_name
        description: "last name of the sales person."
        tests:
          - not_null

      - name: week_start_date
        description: "start date of the week for which sales are aggregated."
        tests:
          - not_null

      - name: num_orders
        description: "total number of orders made by the sales person during the week."
        tests:
          - not_null

      - name: total_products_sold
        description: "total number of products sold by the sales person during the week."
        tests:
          - not_null

      - name: total_sales_value
        description: "total value of sales made by the sales person during the week."
        tests:
          - not_null

      - name: sales_territory_name
        description: "the sales territory region of the sales person."
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_person_id
            - week_start_date
