version: 2

models:
  - name: agg_sales_by_order
    description: "aggregated sales data by order, including order details, payment method, discount flag, and other relevant metrics."
    columns:
      - name: sales_order_id
        description: "unique identifier for the sales order."
        tests:
          - not_null
          - unique

      - name: order_date
        description: "the date when the order was placed."
        tests:
          - not_null

      - name: due_date
        description: "the date when the order is due."
        tests:
          - not_null

      - name: status_name
        description: "the status of the order."
        tests:
          - not_null

      - name: sales_person_id
        description: "identifier for the salesperson associated with the order."
        tests:
          - relationships:
              to: ref('dim_sales_person')
              field: sales_person_id

      - name: customer_id
        description: "identifier for the customer who placed the order."
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: sales_territory_id
        description: "sales territory where the order was placed."
        tests:
          - relationships:
              to: ref('dim_sales_territory')
              field: sales_territory_id

      - name: ship_method_name
        description: "shipping method used for the order."
        tests:
          - not_null

      - name: ship_date
        description: "the date when the order was shipped."
        tests:
          - not_null

      - name: online_order_flag
        description: "indicates whether the order was placed online (true) or offline (false)."
        tests:
          - not_null

      - name: store_id
        description: "identifier for the store where the order was processed, if applicable."

      - name: num_order_items
        description: "total number of items in the order."
        tests:
          - not_null

      - name: total_products_ordered
        description: "total quantity of products ordered."
        tests:
          - not_null

      - name: total_sales_value
        description: "total value of the order, including discounts."
        tests:
          - not_null

      - name: avg_item_value
        description: "average value per item in the order, adjusted for discounts."
        tests:
          - not_null

      - name: payment_method
        description: "payment method used for the order."
        tests:
          - not_null

      - name: sales_reasons
        description: "aggregated reasons for the sale, if applicable."

      - name: has_discount
        description: "flag indicating whether the order had a discount applied based on the special_offer_id."
        tests:
          - not_null
