version: 2

models:
  - name: dim_sales_person
    description: "This table contains detailed sales person information, including their associated sales territory, financial metrics, and personal details."
    columns:
      - name: sales_person_id
        description: "Unique identifier for the sales person."
        tests:
          - unique
          - not_null

      - name: business_entity_id
        description: "Unique identifier for the business entity associated with the sales person."
        tests:
          - not_null

      - name: first_name
        description: "First name of the sales person."
        tests:
          - not_null

      - name: last_name
        description: "Last name of the sales person."
        tests:
          - not_null

      - name: sales_territory_id
        description: "Identifier for the sales territory associated with the sales person."
        tests:
          - relationships:
              to: ref('dim_sales_territory')
              field: sales_territory_id

      - name: territory_name
        description: "Name of the sales territory associated with the sales person."

      - name: country_region_id
        description: "Identifier for the country or region associated with the sales territory."

      - name: sales_quota
        description: "The sales quota assigned to the sales person."

      - name: bonus
        description: "Bonus amount for the sales person."
        tests:
          - not_null

      - name: commission_pct
        description: "Commission percentage for the sales person."
        tests:
          - not_null

      - name: sales_ytd
        description: "Year-to-date sales for the sales person."
        tests:
          - not_null

      - name: sales_last_year
        description: "Sales for the previous year."
        tests:
          - not_null
