version: 2

models:
  - name: agg_sales_by_store
    description: "aggregated sales data by store, including sales details by week, total sales value, and other relevant metrics."
    columns:
      - name: store_id
        description: "unique identifier for the store."
        tests:
          - not_null

      - name: store_name
        description: "name of the store."
        tests:
          - not_null

      - name: week_start_date
        description: "start date of the week for which sales are aggregated."
        tests:
          - not_null

      - name: num_orders
        description: "total number of orders made by the store during the week."
        tests:
          - not_null

      - name: total_products_sold
        description: "total number of products sold by the store during the week."
        tests:
          - not_null

      - name: total_sales_value
        description: "total value of sales made by the store during the week."
        tests:
          - not_null

      - name: avg_sales_value_per_order
        description: "average sales value per order made by the store during the week."
        tests:
          - not_null

      - name: avg_products_per_order
        description: "average number of products per order made by the store during the week."
        tests:
          - not_null

      - name: state_province_name
        description: "the state or province where the store is located."
        tests:
          - not_null

      - name: country_region_name
        description: "the country or region where the store is located."
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - store_id
            - week_start_date
