version: 2

models:
  - name: dim_store
    description: "This table contains information about stores, including their geographic location and associated salespersons."
    columns:
      - name: store_id
        description: "Unique identifier for the store."
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: "Business entity identifier associated with the store."
      - name: store_name
        description: "Name of the store."
        tests:
          - not_null
      - name: sales_person_id
        description: "Salesperson identifier associated with the store."
      - name: demographics
        description: "Demographic details of the store."
      - name: state_province_name
        description: "Name of the state or province where the store is located."
        tests:
          - not_null
      - name: city_district_name
        description: "Name of the city or district where the store is located."
        tests:
          - not_null
      - name: country_region_name
        description: "Name of the country or region where the store is located."
        tests:
          - not_null
