version: 2

models:
  - name: dim_customer
    description: "This table contains detailed customer information, including personal details, store, sales territory, and address-related data."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for the customer."
        tests:
          - not_null
          - unique

      - name: person_id
        description: "Foreign key to the person entity. Can be null."

      - name: store_id
        description: "Foreign key to the store entity. Can be null."

      - name: sales_territory_id
        description: "Foreign key to the sales territory entity. Can be null."

      - name: first_name
        description: "First name of the customer."

      - name: middle_name
        description: "Middle name of the customer."

      - name: last_name
        description: "Last name of the customer."

      - name: name_title
        description: "Title of the customer."

      - name: person_type
        description: "Type of person (individual or organization)."

      - name: name_suffix
        description: "Suffix of the customer's name."

      - name: email_promotion
        description: "Indicates whether the customer is open to email promotions."

      - name: email_address
        description: "Email address of the customer."

      - name: state_province_id
        description: "Foreign key to the state or province entity."

      - name: state_province_name
        description: "Name of the state or province associated with the customer."

      - name: city_district_id
        description: "Foreign key to the city or district entity."

      - name: city_district_name
        description: "Name of the city or district associated with the customer."

      - name: country_region_id
        description: "Foreign key to the country or region entity."

      - name: country_region_name
        description: "Name of the country or region associated with the customer."

      - name: address_type_name
        description: "Type of the address, based on the address type ID."
