version: 2

models:
  - name: dim_product
    description: "This table contains detailed product information, including attributes like category, subcategory, model, and pricing."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - unique
          - not_null

      - name: product_name
        description: "The name of the product."
        tests:
          - not_null

      - name: product_number
        description: "The product number for identification."
        tests:
          - not_null

      - name: product_category_id
        description: "Identifier for the product category."

      - name: product_category_name
        description: "Name of the product category."

      - name: product_subcategory_id
        description: "Identifier for the product subcategory."

      - name: product_subcategory_name
        description: "Name of the product subcategory."

      - name: product_model_id
        description: "Identifier for the product model."

      - name: product_model_name
        description: "Name of the product model."

      - name: product_line
        description: "Product line category."

      - name: class
        description: "Product class."

      - name: style
        description: "Product style."

      - name: color
        description: "Color of the product."

      - name: size
        description: "Size of the product."

      - name: size_unit_measure_name
        description: "Unit measure name for the size."

      - name: weight
        description: "Weight of the product."

      - name: weight_unit_measure_name
        description: "Unit measure name for the weight."

      - name: standard_cost
        description: "Standard cost of the product."
        tests:
          - not_null

      - name: list_price
        description: "List price of the product."
        tests:
          - not_null

      - name: sell_start_date
        description: "Start date of the product sale."
        tests:
          - not_null

      - name: sell_end_date
        description: "End date of the product sale."

      - name: discontinued_date
        description: "Date when the product was discontinued."

      - name: finished_goods_flag
        description: "Flag indicating if the product is a finished good."
        tests:
          - not_null
