version: 2

models:
  - name: agg_sales_by_sales_territory
    description: "Aggregated sales data by sales territory, including sales details by week."
    columns:
      - name: sales_territory_id
        description: "Unique identifier for the sales territory."
        tests:
          - not_null

      - name: sales_territory_name
        description: "The name of the sales territory."
        tests:
          - not_null

      - name: week_start_date
        description: "Start date of the week for which sales are aggregated."
        tests:
          - not_null

      - name: num_orders
        description: "Total number of orders made in the sales territory during the week."
        tests:
          - not_null

      - name: total_products_sold
        description: "Total number of products sold in the sales territory during the week."
        tests:
          - not_null

      - name: total_sales_value
        description: "Total value of sales made in the sales territory during the week."
        tests:
          - not_null

      - name: num_customers
        description: "Total number of unique customers in the sales territory during the week."
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_territory_id
            - week_start_date
