{{ config(
  materialized='view',
  schema='stg_adventure_works',
  description='this model standardizes the product cost history data, introducing a new primary key generated by row_number() and ensuring data consistency and uniqueness of the combination of product_id and start_date.'
) }}

with stg_product_cost_history as (
    select
        row_number() over (order by productid, startdate) as product_cost_history_id
      , cast(productid as int64) as product_id
      , cast(startdate as datetime) as start_date
      , cast(enddate as datetime) as end_date
      , cast(standardcost as float64) as standard_cost
      , cast(modifieddate as datetime) as last_modified_date
    from
        {{ source('stg_adventure_works', 'productcosthistory') }}
)

select
    product_cost_history_id
  , product_id
  , start_date
  , end_date
  , standard_cost
  , last_modified_date
from
    stg_product_cost_history
order by
    product_cost_history_id
