version: 2
models:
  - name: stg_employee
    description: This model standardizes the employee data and enforces the foreign key
      constraint on business_entity_id which is also the primary key.
    columns:
      - name: business_entity_id
        description: Unique identifier for each employee, also a foreign key referencing
          the person table.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_person')
              field: business_entity_id
      - name: job_title
        description: Job title of the employee.
        tests:
          - not_null
