version: 2
models:
  - name: stg_department
    description: This model standardizes the department data, ensuring names are
      capitalized, replaces null values in the `GroupName` column, and adds a
      unique primary key `department_id`.
    columns:
      - name: department_id
        description: Unique identifier for each department.
        tests:
          - unique
          - not_null
      - name: department_name
        description: Name of the department.
        tests:
          - not_null
          - unique
      - name: group_name
        description: Name of the group to which the department belongs. Replaced with
          'Unknown Group' when null.
        tests:
          - not_null
      - name: last_modified_date
        description: Date and time when the department data was last modified, converted
          from string.
        tests:
          - not_null

  - name: stg_shift
    description: This model standardizes the shift data, ensuring that the shift
      name is unique, validating the start and end times, and adding a unique
      primary key shift_id.
    columns:
      - name: shift_id
        description: Unique identifier for each shift.
        tests:
          - unique
          - not_null
      - name: shift_name
        description: Name of the shift.
        tests:
          - unique
          - not_null
      - name: start_time
        description: Start time of the shift.
        tests:
          - not_null
      - name: end_time
        description: End time of the shift.
        tests:
          - not_null
      - name: last_modified_date
        description: Date and time when the shift data was last modified, converted from
          string.
        tests:
          - not_null
    tests:
      - unique_combination:
          combination_of:
            - start_time
            - end_time

  - name: stg_job_candidate
    description: This model standardizes the job candidate data, ensuring that
      job_candidate_id is the primary key, allowing for nullable
      business_entity_id as a foreign key, and validating the modified date.
    columns:
      - name: job_candidate_id
        description: Unique identifier for each job candidate.
        tests:
          - not_null
          - unique
      - name: business_entity_id
        description: Foreign key referencing the business entity ID. This can be null if
          the candidate was not hired.
        tests:
          - relationships:
              to: ref('stg_employee')
              field: business_entity_id
      - name: job_candidate_resume
        description: Resume of the job candidate in XML.
      - name: last_modified_date
        description: Date and time when the job candidate data was last modified,
          converted from string.
        tests:
          - not_null

  - name: stg_employee_pay_history
    description: This model creates a new primary key column `employee_pay_history_id`,
      ensures `rate` is a float, defines `rate_change_date` as unique, and establishes
      `business_entity_id` as a foreign key referencing the `employee` table.
    columns:
      - name: employee_pay_history_id
        description: Unique identifier for each employee pay history record.
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: Foreign key referencing the business entity ID from the employee
          table. This can be null if not associated with a specific entity.
        tests:
          - not_null
          - relationships:
              to: ref('stg_employee')
              field: business_entity_id
      - name: rate_change_date
        description: Date the change in pay is effective.
        tests:
          - not_null
      - name: rate
        description: The pay rate for the employee, stored as a float.
        tests:
          - not_null
      - name: pay_frequency
        description: The frequency of pay, stored as an integer. 1 = Salary received
          monthly, 2 = Salary received biweekly.
        tests:
          - not_null
      - name: last_modified_date
        description: Date and time when the pay history record was last modified,
          converted from string.
        tests:
          - not_null
    tests:
      - unique_combination:
          combination_of:
            - business_entity_id
            - rate_change_date

  - name: stg_employee_department_history
    description: This model creates a new primary key column `employee_department_history_id`,
      transforms dates, ensures key constraints, and sets `start_date` as non-nullable.
    columns:
      - name: employee_department_history_id
        description: Unique identifier for each employee department history record.
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: Foreign key referencing the business entity ID from the employee table.
        tests:
          - not_null
          - relationships:
              to: ref('stg_employee')
              field: business_entity_id
      - name: department_id
        description: Foreign key referencing the department ID.
        tests:
          - not_null
          - relationships:
              to: ref('stg_department')
              field: department_id
      - name: shift_id
        description: Foreign key referencing the shift ID.
        tests:
          - not_null
          - relationships:
              to: ref('stg_shift')
              field: shift_id
      - name: start_date
        description: The date when the employee started in the department, stored as a
          datetime.
        tests:
          - not_null
      - name: end_date
        description: The date when the employee ended in the department, stored as a
          datetime. NULL = Current department.
      - name: last_modified_date
        description: Date and time when the department history record was last modified,
          converted from string.
        tests:
          - not_null
    tests:
      - unique_combination:
          combination_of:
            - employee_department_history_id
            - business_entity_id
            - department_id
            - shift_id

  - name: stg_employee
    description: This model standardizes the employee data, ensures the uniqueness
      of national_id_number, login_id, and rowguid, and enforces the foreign key
      constraint on business_entity_id which is also the primary key.
    columns:
      - name: employee_id
        description: Unique identifier for each employee, also a foreign key referencing
          the person table.
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: Unique identifier for each employee, also a foreign key referencing
          the person table.
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_person')
              field: business_entity_id
      - name: national_id_number
        description: Unique national ID number for each employee.
        tests:
          - unique
          - not_null
      - name: login_id
        description: Unique login ID for each employee.
        tests:
          - unique
          - not_null
      - name: organization_node
        description: Where the employee is located in the corporate hierarchy.
      - name: job_title
        description: Job title of the employee.
        tests:
          - not_null
      - name: birth_date
        description: Date of birth of the employee, stored as datetime.
        tests:
          - not_null
      - name: marital_status
        description: Marital status of the employee. M = Married, S = Single.
        tests:
          - not_null
      - name: gender
        description: Gender of the employee. M = Male, F = Female.
        tests:
          - not_null
      - name: hire_date
        description: Date when the employee was hired, stored as datetime.
        tests:
          - not_null
      - name: salaried_flag
        description: "Job classification. 0 = Hourly, not exempt from collective
          bargaining. 1 = Salaried, exempt from collective bargaining. Default:
          1"
        tests:
          - not_null
      - name: vacation_hours
        description: Number of available vacation hours.
        tests:
          - not_null
      - name: sick_leave_hours
        description: Number of available sick leave hours.
        tests:
          - not_null
      - name: current_flag
        description: Indicates if the employee is currently active (true or false).
        tests:
          - not_null
      - name: row_guid
        description: Unique identifier for each employee row, used for replication.
        tests:
          - unique
          - not_null
      - name: last_modified_date
        description: Date and time when the employee data was last modified, converted
          from string.
        tests:
          - not_null
