version: 2

models:
  - name: stg_store
    description: "this model standardizes the store data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: store_id
        description: "unique identifier for each store record, generated based on the order of businessentityid."
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: "primary key. foreign key to businessentity.businessentityid."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_business_entity')
              field: business_entity_id
      - name: store_name
        description: "name of the store."
        tests:
          - not_null
      - name: sales_person_id
        description: "foreign key to salesperson.salespersonid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales_person')
              field: sales_person_id
      - name: demographics
        description: "demographic information about the store."

  - name: stg_customer
    description: "this model standardizes the customer data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: customer_id
        description: "unique identifier for each customer record."
        tests:
          - unique
          - not_null
      - name: person_id
        description: "foreign key to person.personid."
        tests:
          - relationships:
              to: ref('stg_person')
              field: business_entity_id
      - name: store_id
        description: "foreign key to store.storeid."
        tests:
          - relationships:
              to: ref('stg_store')
              field: business_entity_id
      - name: sales_territory_id
        description: "foreign key to salesterritory.salesterritoryid."
        tests:
          - relationships:
              to: ref('stg_sales_territory')
              field: sales_territory_id

  - name: stg_sales_person_quota_history
    description: "this model standardizes the sales person quota history data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: sales_person_quota_history_id
        description: "unique identifier for each sales person quota history record."
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: "foreign key to salesperson.businessentityid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales_person')
              field: business_entity_id
      - name: quota_date
        description: "sales quota date."
        tests:
          - not_null
      - name: sales_quota
        description: "sales quota amount."
        tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - business_entity_id
            - quota_date

  - name: stg_sales_person
    description: "this model standardizes the sales person data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: sales_person_id
        description: "unique identifier for each sales person record."
        tests:
          - unique
          - not_null
      - name: business_entity_id
        description: "foreign key to employee.businessentityid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_employee')
              field: business_entity_id
      - name: sales_territory_id
        description: "foreign key to salesterritory.territoryid."
        tests:
          - relationships:
              to: ref('stg_sales_territory')
              field: sales_territory_id
      - name: sales_quota
        description: "projected yearly sales."
      - name: bonus
        description: "bonus due if quota is met."
        tests:
          - not_null
      - name: commission_pct
        description: "commission percent received per sale."
        tests:
          - not_null
      - name: sales_ytd
        description: "sales total year to date."
        tests:
          - not_null
      - name: sales_last_year
        description: "sales total of previous year."
        tests:
          - not_null

  - name: stg_sales_territory
    description: "this model standardizes the sales territory data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: sales_territory_id
        description: "unique identifier for each sales territory record."
        tests:
          - unique
          - not_null

      - name: sales_territory_name
        description: "name of the sales territory."
        tests:
          - not_null
          - unique

      - name: country_region_id
        description: "foreign key to stateprovince.countryregionid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_country_region')
              field: country_region_id

      - name: territory_group
        description: "group associated with the sales territory."
        tests:
          - not_null
      - name: sales_ytd
        description: "year to date sales."
        tests:
          - not_null
      - name: sales_last_year
        description: "sales total from the previous year."
        tests:
          - not_null
      - name: cost_ytd
        description: "year to date cost."
        tests:
          - not_null
      - name: cost_last_year
        description: "cost total from the previous year."
        tests:
          - not_null

  - name: stg_special_offer
    description: "this model standardizes the special offer data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: special_offer_id
        description: "unique identifier for each special offer record."
        tests:
          - unique
          - not_null
      - name: offer_description
        description: "description of the special offer."
        tests:
          - not_null
      - name: discount_pct
        description: "discount percentage applied in the special offer."
        tests:
          - not_null
      - name: offer_type
        description: "type of the special offer."
        tests:
          - not_null
      - name: offer_category
        description: "category of the special offer."
        tests:
          - not_null
      - name: start_date
        description: "start date of the special offer."
        tests:
          - not_null
      - name: end_date
        description: "end date of the special offer."
        tests:
          - not_null
      - name: min_qty
        description: "minimum quantity required for the special offer."
        tests:
          - not_null
      - name: max_qty
        description: "maximum quantity allowed for the special offer."

  - name: stg_special_offer_product
    description: "this model standardizes the special offer product data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: special_offer_id
        description: "foreign key to specialoffer.specialofferid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_special_offer')
              field: special_offer_id
      - name: product_id
        description: "foreign key to product.productid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_product')
              field: product_id

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - special_offer_id
            - product_id

  - name: stg_sales_reason
    description: "this model standardizes the sales reason data, ensuring data consistency and validating key constraints, unique identifiers, and relationships."
    columns:
      - name: sales_reason_id
        description: "primary key for salesreason records."
        tests:
          - unique
          - not_null
      - name: name
        description: "sales reason description."
        tests:
          - not_null
      - name: reason_type
        description: "category the sales reason belongs to."
        tests:
          - not_null

  - name: stg_sales_order_header_sales_reason
    description: "this model standardizes the sales order header sales reason data, ensuring data consistency and validating the primary key and foreign key relationships."
    columns:
      - name: sales_order_id
        description: "the sales order identification number."
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales_order_header')
              field: sales_order_id
      - name: sales_reason_id
        description: "the sales reason identification number."
        tests:
          - not_null
          - relationships:
              to: ref('stg_sales_reason')
              field: sales_reason_id

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_order_id
            - sales_reason_id

  - name: stg_sales_order_detail
    description: "this model standardizes the sales order detail data, ensuring data consistency and validating key constraints and values."
    columns:
      - name: sales_order_id
        description: "primary key for the sales order detail, referencing the sales order header."
        tests:
          - not_null

      - name: sales_order_detail_id
        description: "primary key for the sales order detail, unique per order."
        tests:
          - not_null

      - name: product_id
        description: "product identification number associated with the sales order detail."
        tests:
          - not_null

      - name: special_offer_id
        description: "special offer identification number associated with the sales order detail."
        tests:
          - not_null

      - name: carrier_tracking_number
        description: "shipment tracking number supplied by the shipper."

      - name: order_qty
        description: "quantity ordered per product."
        tests:
          - not_null

      - name: unit_price
        description: "selling price of a single product."
        tests:
          - not_null

      - name: unit_price_discount
        description: "discount amount applied to the unit price."
        tests:
          - not_null

      - name: line_total
        description: "Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty."
        tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_order_id
            - sales_order_detail_id

  - name: stg_currency
    description: "this model standardizes the currency data, ensuring data consistency and validating key constraints and values."
    columns:
      - name: currency_code
        description: "the iso code for the currency."
        tests:
          - not_null
          - unique

      - name: name
        description: "the name of the currency."
        tests:
          - not_null
          - unique

  - name: stg_currency_rate
    description: "this model standardizes the currency rate data, ensuring data consistency and validating key constraints and values."
    columns:
      - name: currency_rate_id
        description: "primary key for currencyrate records."
        tests:
          - not_null
          - unique

      - name: currency_rate_date
        description: "date and time the exchange rate was obtained."
        tests:
          - not_null

      - name: from_currency_code
        description: "exchange rate was converted from this currency code."
        tests:
          - not_null
          - relationships:
              to: ref('stg_currency')
              field: currency_code

      - name: to_currency_code
        description: "exchange rate was converted to this currency code."
        tests:
          - not_null
          - relationships:
              to: ref('stg_currency')
              field: currency_code

      - name: average_rate
        description: "average exchange rate for the day."
        tests:
          - not_null

      - name: end_of_day_rate
        description: "final exchange rate for the day."
        tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - from_currency_code
            - to_currency_code
            - currency_rate_date

  - name: stg_sales_order_header
    description: "this model standardizes the sales order header data, ensuring data consistency and validating key constraints and values."
    columns:
      - name: sales_order_id
        description: "primary key for salesorderheader records."
        tests:
          - not_null
          - unique

      - name: revision_number
        description: "incremental number to track changes to the sales order over time."
        tests:
          - not_null

      - name: order_date
        description: "dates the sales order was created."
        tests:
          - not_null

      - name: due_date
        description: "date the order is due to the customer."
        tests:
          - not_null

      - name: ship_date
        description: "date the order was shipped to the customer."

      - name: status
        description: "order current status. 1 = in process; 2 = approved; 3 = backordered; 4 = rejected; 5 = shipped; 6 = cancelled."
        tests:
          - not_null

      - name: online_order_flag
        description: "0 = order placed by sales person. 1 = order placed online by customer."
        tests:
          - not_null

      - name: purchase_order_number
        description: "customer purchase order number reference."

      - name: account_number
        description: "financial accounting number reference."

      - name: customer_id
        description: "customer identification number. foreign key to customer.customerid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_customer')
              field: customer_id

      - name: sales_person_id
        description: "sales person who created the sales order. foreign key to salesperson.businessentityid."
        tests:
          - relationships:
              to: ref('stg_sales_person')
              field: sales_person_id

      - name: sales_territory_id
        description: "territory in which the sale was made. foreign key to salesterritory.salesterritoryid."
        tests:
          - relationships:
              to: ref('stg_sales_territory')
              field: sales_territory_id

      - name: ship_method_id
        description: "shipping method. foreign key to shipmethod.shipmethodid."
        tests:
          - not_null
          - relationships:
              to: ref('stg_ship_method')
              field: ship_method_id

      - name: credit_card_id
        description: "credit card identification number."

      - name: credit_card_approval_code
        description: "approval code provided by the credit card company."

      - name: currency_rate_id
        description: "currency exchange rate used. foreign key to currencyrate.currencyrateid."
        tests:
          - relationships:
              to: ref('stg_currency_rate')
              field: currency_rate_id

      - name: sub_total
        description: "sales subtotal."
        tests:
          - not_null

      - name: tax_amount
        description: "tax amount."
        tests:
          - not_null

      - name: freight
        description: "shipping cost."
        tests:
          - not_null

      - name: total_due
        description: "total due from customer. computed as subtotal + taxamt + freight."
        tests:
          - not_null

      - name: comment
        description: "additional order information."
