version: 2

models:
  - name: int_store_info
    description: "Intermediate view in the dev_adventure_works schema containing detailed store information, including location data."
    columns:
      - name: store_id
        description: "Unique identifier for the store."
        tests:
          - not_null
          - unique
      - name: business_entity_id
        description: "Unique identifier for the business entity associated with the store."
        tests:
          - not_null
      - name: store_name
        description: "Name of the store."
        tests:
          - not_null
      - name: sales_person_id
        description: "Identifier for the sales person associated with the store."
        tests:
          - not_null
      - name: state_province_id
        description: "Identifier for the state or province."
        tests:
          - relationships:
              to: ref('stg_state_province')
              field: state_province_id
      - name: state_province_name
        description: "Name of the state or province."
        tests:
          - not_null
      - name: city_district_id
        description: "Identifier for the city or district."
        tests:
          - relationships:
              to: ref('stg_city_district')
              field: city_district_id
      - name: city_district_name
        description: "Name of the city or district."
        tests:
          - not_null
      - name: country_region_id
        description: "Identifier for the country or region."
        tests:
          - relationships:
              to: ref('stg_country_region')
              field: country_region_id
      - name: country_region_name
        description: "Name of the country or region."
        tests:
          - not_null
