version: 2

models:
  - name: stg_vendor
    description: "This model standardizes the vendor data, ensures the uniqueness of accountnumber, and enforces the foreign key constraint on businessentityid which is also the primary key."
    columns:
      - name: business_entity_id
        description: "Primary key for Vendor records. Foreign key to BusinessEntity.BusinessEntityID."
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_business_entity')
              field: business_entity_id

      - name: account_number
        description: "Vendor account (identification) number."
        tests:
          - unique
          - not_null

      - name: vendor_name
        description: "Company name of the vendor."
        tests:
          - not_null

      - name: credit_rating
        description: "Credit rating assigned to the vendor. 1 = Superior, 2 = Excellent, 3 = Above average, 4 = Average, 5 = Below average."
        tests:
          - not_null

      - name: preferred_vendor_status
        description: "Indicates whether the vendor has preferred status. 0 = Do not use if another vendor is available. 1 = Preferred over other vendors supplying the same product."
        tests:
          - not_null

      - name: active_flag
        description: "Indicates whether the vendor is currently active. 0 = Vendor no longer used. 1 = Vendor is actively used."
        tests:
          - not_null

      - name: purchasing_web_service_url
        description: "URL of the vendor's purchasing web service."

      - name: last_modified_date
        description: "Date and time when the vendor data was last modified."
        tests:
          - not_null

  - name: stg_ship_method
    description: "This model standardizes the ship method data, ensuring data consistency and enforcing the foreign key constraint on shipmethodid, which is also the primary key."
    columns:
      - name: ship_method_id
        description: "Primary key for ShipMethod records."
        tests:
          - unique
          - not_null

      - name: ship_method_name
        description: "Shipping company name."
        tests:
          - unique
          - not_null

      - name: ship_base
        description: "Minimum shipping charge."
        tests:
          - not_null

      - name: ship_rate
        description: "Shipping charge per pound."
        tests:
          - not_null

      - name: row_guid
        description: "ROWGUIDCOL number uniquely identifying the record."
        tests:
          - unique
          - not_null

      - name: last_modified_date
        description: "Date and time when the ship method data was last modified."
        tests:
          - not_null

  - name: stg_product_vendor
    description: "This model standardizes the product vendor data, ensuring data consistency and using unit_measure_id as a foreign key, populated from the stg_unit_measure table."
    columns:
      - name: product_id
        description: "Product identification number. Foreign key to Product.ProductID."
        tests:
          - not_null
          - relationships:
              to: ref('stg_product')
              field: product_id

      - name: business_entity_id
        description: "Vendor identification number. Foreign key to Vendor.BusinessEntityID."
        tests:
          - not_null
          - relationships:
              to: ref('stg_vendor')
              field: business_entity_id

      - name: average_lead_time
        description: "The average lead time (in days) for the vendor to deliver the product."
        tests:
          - not_null

      - name: standard_price
        description: "Standard price that the vendor charges for the product."
        tests:
          - not_null

      - name: last_receipt_cost
        description: "Cost of the product during the last receipt."

      - name: last_receipt_date
        description: "Date when the product was last received."

      - name: min_order_qty
        description: "Minimum quantity that can be ordered from the vendor."
        tests:
          - not_null

      - name: max_order_qty
        description: "Maximum quantity that can be ordered from the vendor."
        tests:
          - not_null

      - name: unit_measure_id
        description: "Unique identifier for the unit of measure, referencing the stg_unit_measure table."
        tests:
          - not_null
          - relationships:
              to: ref('stg_unit_measure')
              field: unit_measure_id

      - name: last_modified_date
        description: "Date and time when the product vendor data was last modified."
        tests:
          - not_null
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_id
            - business_entity_id

  - name: stg_purchase_order_header
    description: "This model standardizes the purchase order header data, ensuring data consistency and enforcing the foreign key constraints on vendorid, employeeid, and shipmethodid."
    columns:
      - name: purchase_order_id
        description: "Primary key for PurchaseOrderHeader records."
        tests:
          - unique
          - not_null

      - name: revision_number
        description: "Incremental number to track changes to the purchase order over time."
        tests:
          - not_null

      - name: status
        description: "Order current status. 1 = Pending, 2 = Approved, 3 = Rejected, 4 = Complete."
        tests:
          - not_null

      - name: employee_id
        description: "Employee who created the purchase order. Foreign key to Employee.BusinessEntityID."
        tests:
          - not_null
          - relationships:
              to: ref('stg_employee')
              field: employee_id

      - name: vendor_id
        description: "Vendor from whom the items are purchased. Foreign key to Vendor.BusinessEntityID."
        tests:
          - not_null
          - relationships:
              to: ref('stg_vendor')
              field: business_entity_id

      - name: ship_method_id
        description: "Shipping method used for the purchase order. Foreign key to ShipMethod.ShipMethodID."
        tests:
          - not_null
          - relationships:
              to: ref('stg_ship_method')
              field: ship_method_id

      - name: order_date
        description: "Date the purchase order was created."
        tests:
          - not_null

      - name: ship_date
        description: "Date the items were shipped."

      - name: sub_total
        description: "Subtotal before tax and freight."
        tests:
          - not_null

      - name: tax_amount
        description: "Tax amount for the purchase order."
        tests:
          - not_null

      - name: freight
        description: "Shipping cost."
        tests:
          - not_null

      - name: last_modified_date
        description: "Date and time when the purchase order header was last modified."
        tests:
          - not_null

  - name: stg_purchase_order_detail
    description: "This model standardizes the purchase order detail data, ensuring data consistency and enforcing the foreign key constraints on purchaseorderid and productid."
    columns:
      - name: purchase_order_id
        description: "Primary key of the purchase order header to which this detail is related."
        tests:
          - not_null
          - relationships:
              to: ref('stg_purchase_order_header')
              field: purchase_order_id

      - name: purchase_order_detail_id
        description: "Primary key of the purchase order detail, unique within each purchase order."
        tests:
          - not_null

      - name: due_date
        description: "Date by which the products should be received."
        tests:
          - not_null

      - name: order_qty
        description: "Quantity of products ordered."
        tests:
          - not_null

      - name: product_id
        description: "Foreign key to Product.ProductID."
        tests:
          - not_null
          - relationships:
              to: ref('stg_product')
              field: product_id

      - name: unit_price
        description: "Unit price of the product at the time of the order."
        tests:
          - not_null

      - name: received_qty
        description: "Quantity of products actually received."
        tests:
          - not_null

      - name: rejected_qty
        description: "Quantity of products rejected upon receipt."
        tests:
          - not_null

      - name: last_modified_date
        description: "Date and time when the purchase order detail was last modified."
        tests:
          - not_null

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - purchase_order_id
            - purchase_order_detail_id
