version: 2

models:
  - name: stg_ship_method
    description: "This model standardizes the ship method data, ensuring data consistency and enforcing the foreign key constraint on shipmethodid, which is also the primary key."
    columns:
      - name: ship_method_id
        description: "Primary key for ShipMethod records."
        tests:
          - unique
          - not_null

      - name: ship_method_name
        description: "Shipping company name."
        tests:
          - unique
          - not_null

      - name: ship_base
        description: "Minimum shipping charge."
        tests:
          - not_null

      - name: ship_rate
        description: "Shipping charge per pound."
        tests:
          - not_null

