version: 2

models:
  - name: agg_sales_by_customer
    description: "Aggregated sales data by customer, including order details, top purchased product, and average values."
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: num_orders
        description: "Total number of orders placed by the customer."
        tests:
          - not_null

      - name: total_products
        description: "Total quantity of products purchased by the customer."
        tests:
          - not_null

      - name: avg_products_per_order
        description: "Average number of products per order for the customer."
        tests:
          - not_null

      - name: total_sales_value
        description: "Total value of all orders placed by the customer."
        tests:
          - not_null

      - name: avg_order_value
        description: "Average value per order, adjusted for discounts."
        tests:
          - not_null

      - name: last_order_date
        description: "Date of the customer's most recent order."
        tests:
          - not_null

      - name: most_purchased_product
        description: "Product most frequently purchased by the customer, based on order quantity."
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: total_qty_with_product
        description: "Total quantity of the most purchased product by the customer."
        tests:
          - not_null

      - name: num_orders_with_product
        description: "Number of orders in which the most purchased product appeared."
        tests:
          - not_null
