version: 2

models:
  - name: agg_sales_by_customer
    description: "Aggregates sales data by customer, allowing for analysis of customer behavior over time."
    columns:
      - name: customer_id
        description: "Unique identifier for the customer."
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: first_name
        description: "Customer's first name."

      - name: last_name
        description: "Customer's last name."

      - name: email_promotion
        description: "Indicator if the customer is enrolled in email promotions."
      - name: country_region_id
        description: "Identifier for the customer's country or region."

      - name: country_region_name
        description: "Name of the customer's country or region."

      - name: sales_territory_id
        description: "Identifier for the sales territory."
        tests:
          - relationships:
              to: ref('dim_sales_territory')
              field: sales_territory_id
      - name: sales_territory_name
        description: "Name of the sales territory."

      - name: sales_territory_group
        description: "Group to which the sales territory belongs."
      - name: store_id
        description: "Identifier for the store where the sale occurred."

      - name: year
        description: "Year of the sale."
      - name: total_sales_value
        description: "Total sales value for the customer in the year."
      - name: total_orders
        description: "Total number of orders made by the customer in the year."
      - name: last_order_date
        description: "Date of the last order made by the customer."
