version: 2

models:
  - name: int_product_info
    description: "Intermediate view in the dev_adventure_works schema containing detailed product information."
    columns:
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Name of the product."
        tests:
          - not_null
          - unique
      - name: product_number
        description: "Product number for identification."
        tests:
          - not_null
          - unique
      - name: make_flag
        description: "Indicates if the product is manufactured in-house ('true') or purchased ('false')."
        tests:
          - not_null
      - name: safety_stock_level
        description: "Minimum inventory quantity."
        tests:
          - not_null
      - name: reorder_point
        description: "Inventory level that triggers a purchase order or work order."
        tests:
          - not_null
      - name: days_to_manufacture
        description: "Number of days required to manufacture the product."
        tests:
          - not_null
      - name: product_category_id
        description: "Identifier for the product category."
        tests:
          - relationships:
              to: ref('stg_product_category')
              field: product_category_id
      - name: product_category_name
        description: "Name of the product category."
      - name: product_subcategory_id
        description: "Identifier for the product subcategory."
        tests:
          - relationships:
              to: ref('stg_product_subcategory')
              field: product_subcategory_id
      - name: product_subcategory_name
        description: "Name of the product subcategory."
      - name: product_model_id
        description: "Identifier for the product model."
        tests:
          - relationships:
              to: ref('stg_product_model')
              field: product_model_id
      - name: product_model_name
        description: "Name of the product model."
      - name: product_line
        description: "Product line code (e.g., R = Road, M = Mountain, T = Touring, S = Standard)."
      - name: class
        description: "Class code of the product (e.g., H = High, M = Medium, L = Low)."
      - name: style
        description: "Style code of the product (e.g., W = Womens, M = Mens, U = Universal)."
      - name: color
        description: "Color of the product."
      - name: size
        description: "Size of the product."
      - name: size_unit_measure_name
        description: "Unit measure name for the size."
      - name: weight
        description: "Weight of the product."
      - name: weight_unit_measure_name
        description: "Unit measure name for the weight."
      - name: standard_cost
        description: "Standard cost of the product."
        tests:
          - not_null
      - name: list_price
        description: "List price of the product."
        tests:
          - not_null
      - name: sell_start_date
        description: "Start date of the product sale."
        tests:
          - not_null
      - name: sell_end_date
        description: "End date of the product sale."
      - name: discontinued_date
        description: "Date when the product was discontinued."
      - name: finished_goods_flag
        description: "Flag indicating if the product is a finished good ('true') or not ('false')."
        tests:
          - not_null
