version: 2

models:
  - name: fact_order_item
    description: "Fact table representing individual order items. Each row represents a product ordered in a specific sales order, along with associated pricing, logistics details, and sales reasons."
    columns:
      - name: sales_order_item_sk
        description: "Surrogate key for the fact table, unique for each combination of sales order, product, and sales order detail."
        tests:
          - unique
          - not_null

      - name: sales_order_id
        description: "Unique identifier for the sales order."
        tests:
          - not_null

      - name: sales_order_detail_id
        description: "Unique identifier for the sales order detail, representing individual products within the order."
        tests:
          - not_null

      - name: product_id
        description: "Unique identifier for the product associated with the sales order."
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id

      - name: customer_id
        description: "Identifier for the customer who placed the order."
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: store_id
        description: "Identifier for the store associated with the customer (business_entity_id)."
        tests:
          - relationships:
              to: ref('dim_store')
              field: business_entity_id

      - name: sales_person_id
        description: "Identifier for the salesperson who created the order."
        tests:
          - relationships:
              to: ref('dim_sales_person')
              field: sales_person_id

      - name: sales_territory_id
        description: "Sales territory where the order was placed."
        tests:
          - relationships:
              to: ref('dim_sales_territory')
              field: sales_territory_id

      - name: payment_method
        description: "Payment method used for the order ('CREDIT CARD' or 'OTHER')."
        tests:
          - not_null

      - name: tax_rate
        description: "Tax rate applied to the order, calculated as tax_amount/sub_total."
        tests:
          - not_null

      - name: avg_unit_freight
        description: "Average shipping cost associated with the order item, calculated by the shipping cost divided by the number of products purchased."
        tests:
          - not_null

      - name: comment
        description: "Sales representative comments regarding the order."

      - name: sales_reason_names
        description: "Aggregated sales reasons, separated by commas."

      - name: sales_reason_types
        description: "Aggregated types of sales reasons, separated by commas."

      - name: line_total
        description: "Total sales amount for the order, calculated from the sales order details."
        tests:
          - not_null

      - name: ship_method_name
        description: "Name of the shipping method used."
        tests:
          - not_null

      - name: ship_base
        description: "Base shipping charge for the order."
        tests:
          - not_null

      - name: ship_rate
        description: "Shipping charge per pound for the order."
        tests:
          - not_null

      - name: from_currency_code
        description: "Currency code for the currency from which the exchange rate is applied."

      - name: to_currency_code
        description: "Currency code for the currency to which the exchange rate is applied."

      - name: average_rate
        description: "The average exchange rate between the from and to currencies."

      - name: order_qty
        description: "Quantity of products ordered in the sales order detail."
        tests:
          - not_null

      - name: unit_price
        description: "Price per unit of the product."
        tests:
          - not_null

      - name: unit_price_discount
        description: "Discount applied to the product unit price."

      - name: special_offer_id
        description: "Identifier for the special offer applied to the product, if any."
        tests:
          - not_null
          - relationships:
              to: ref('dim_special_offer')
              field: special_offer_id

      - name: carrier_tracking_number
        description: "Tracking number for the carrier used to ship the order."

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - sales_order_id
            - sales_order_detail_id
            - product_id
